name: CI - Build, Test, Docker, K8s Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_test:
    name: Build and Test (Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -e -DskipTests=false verify

      - name: Upload jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: target/*.jar